# -*- coding: utf-8 -*-
"""LathnData1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14YmEnEIco5TsOFfarpWpQLiVEPXy00nU
"""

from sklearn.datasets import load_iris
iris = load_iris()
iris

iris.keys()

print(iris.DESCR)

X = iris.data
X.shape

y = iris.target
y.shape

features_name = iris.feature_names
features_name

target_names = iris.target_names
target_names